name: enable-auto-merge

on:
  pull_request:
    # types: [opened]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    name: enable-auto-merge
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'scala-steward'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Enable auto-merge
        run: gh pr merge --auto --merge ${{ github.event.number }}
      - name: Wait checks until finish
        run: gh pr checks ${{ github.event.number }} --watch --fail-fast --required
      - name: Get checks states
        id: checks
        run: |
          states=$(gh pr checks ${{ github.event.number }} --required --json state --jq 'map(.state)|map(select(. != "SUCCESS" and . != "SKIPPED"))')
          echo "states=${states}" | tee -a "${GITHUB_OUTPUT}"
      - run: gh pr review --approve ${{ github.event.number }}
        if: ${{ steps.checks.outputs.states == '[]' }}
